struct GlobalLightingParams {
    ambient_light_color: vec4<f32>,
    ambient_light_intensity: f32,
    quadratic_falloff: u32,
    lighting_enabled: u32,
    shadow_strength: f32,
    fog_color: vec4<f32>,
    film_grain_strength: f32,
    noise_strength: f32,

    light_blending_mode: u32,
    global_light_intensity: f32,
    global_light_color: vec4<f32>,
    vignette_color: vec4<f32>,
    vignette_intensity: f32,
    vignette_radius: f32,
    shake_amount: f32,
    time: f32,
    color_balance: vec4<f32>,
    global_brightness: f32,
    debug_visualization: u32,
    gamma_correction: f32,
    use_lut: u32,
    exposure: f32,
    gamma: f32,
    pre_saturation: f32,
    post_saturation: f32,
    resolution: vec2<f32>,
    chromatic_aberration: f32,
    bloom_threshold: f32,
    bloom_lerp: f32,
    bloom_gamma: f32,
}
